# Generated by Django 4.0.3 on 2022-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='party',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='votes',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
