# Generated by Django 4.0.3 on 2022-06-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_party_party_name_delete_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.party'),
        ),
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
